[package]
name = "passgen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.97", features = ["backtrace"] }
clap = { version = "4.5.32", features = ["derive"] }
cli-clipboard = "0.4.0"
rand = "0.9.0"
thiserror = "2.0.12"
